apiVersion: v1
kind: Service
metadata:
  name: simple-paste-api
  labels:
    app: simple-paste-api-service

spec:
  type: ClusterIP
  selector:
    app: simple-paste-api
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
